name: pysat-env

channels:
    - conda-forge
    - defaults

dependencies:
    - python=3.7
    - numpy
    - scipy
    - h5py
    - matplotlib
    - pandas
    - shapely
    - rasterstats
    - rasterio
    - jupyter
    - spyder
    - conda-build
